version: '3.9'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyectofacturacion
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "9896:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  facturacion_app:
    build: .
    image: karlamendez/facturacion-app:1.0
    container_name: facturacion_app
    restart: always
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/proyectofacturacion
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "9898:9898"

volumes:
  mysql_data: